### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by Jilberta** [mishozhghenti/CiaoAmico#1]
1) EditText-ები შევცვალოთ FloatingEditText-ებით.

2) აპლიკაციის ფორმაში, ყველა ველს თავზე TextView-თი დავაწეროთ Label-ი.

3) Save ღილაკი დავაცენტრიროთ.

4) Save-ის ნაცვლად დავაწეროთ "Send"

5) აპლიკაციის გვერდზე ზევით Back "<-" Menu Button ქონდეს.

6) Time-ების ველები ჰორიზონტალურად იყოს სიმეტრიული.

7) Material Design-ის Default View-ები გვქონდეს.

8) EditText-ებში Padding-ები დავანავაროტოთ.

**Comment by mishozhghenti** [comment]
გავასწორე ესენი. მე-2-ში თავზე დაწერა Label-ის დავტოვე.მუშის სახელის ქვევით დავწერო ანუ Date ?
